# Workflow derived from
# https://github.com/Gilead-BioStats/qcthat/tree/v0.3.0/inst/workflows/qcthat-pr_issues.yaml.
on:
  pull_request:
  # NOTE: This workflow cannot be triggered when an issue is connected to (or
  # disconnected from) the pull request via the "Development" UI of the PR or
  # issue. In that situation, either trigger the workflow manually, or edit the
  # PR body to mention the issue (such as "Closes #55").
    types: [opened, edited, reopened, synchronize]
  workflow_dispatch:
    inputs:
      pr:
        description: PR number to which comment should be added (leave blank for none).
        required: false

name: qcthat PR-Associated Issues Report

permissions:
  # Required for report.
  issues: read
  # Required to add report to pull requests as a comment.
  pull-requests: write

jobs:
  qcthat-pr_issues:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v5

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: local::., Gilead-BioStats/qcthat@main

      - name: Generate PR-Associated Issues QC Report
        run: |
          prNumber <- if ("${{ github.event_name }}" == "pull_request") {
            ${{ github.event.pull_request.number }}
          } else if ("${{ inputs.pr }}" != "") {
            ${{ inputs.pr }}
          } else {
            NA_integer_
          }

          if (is.na(prNumber)) {
            cli::cli_abort("Could not determine PR number.")
          }

          IssueTestMatrix <- qcthat::QCPR(intPRNumber = prNumber)
          print(IssueTestMatrix)

          # Also print to a file.
          print(IssueTestMatrix, con = "qc_report.txt")
        shell: Rscript {0}

      # Delete or comment out this step to prevent PR comments.
      - name: Add comment to PR
        uses: actions/github-script@v6
        with:
          script: |
            let prNumber;
            if (context.eventName === 'pull_request') {
              prNumber = context.issue.number;
            } else if (context.payload.inputs.pr) {
              prNumber = context.payload.inputs.pr;
            }

            if (!prNumber) {
              console.log('Could not determine PR number. Skipping comment.');
              return;
            }

            const fs = require('fs');
            let reportContent;
            try {
              reportContent = fs.readFileSync('qc_report.txt', 'utf8');
            } catch (err) {
              console.error('Error reading qc_report.txt:', err);
              core.setFailed('Failed to read qc_report.txt');
              return;
            }

            const lines = reportContent.split(/[\r\n]+/).filter(line => line.trim() !== '');

            if (lines.length < 2) {
              console.log('Report has less than 2 non-empty lines. Skipping comment.');
              return;
            }

            const reportSummary = lines[0];
            const reportOutcome = lines[lines.length - 1];
            const bodyContent = lines.slice(1, -1).join('\n');

            const commentBody = `
            ## [{qcthat}](https://gilead-biostats.github.io/qcthat/) Report: PR-Associated Issues

            <details>
            <summary>${reportSummary}</summary>

            \`\`\`
            ${bodyContent}
            \`\`\`

            </details>

            ${reportOutcome}
            `;

            try {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: commentBody,
              });
            } catch (error) {
              console.error(`Error creating comment: ${error.message}`);
              core.setFailed(`Failed to create PR comment: ${error.message}`);
            };
