# Workflow derived from
# https://github.com/Gilead-BioStats/qcthat/tree/v1.1.0/inst/workflows/qcthat-completed_issues.yaml.
on:
  push:
    branches: [main]
  pull_request:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to which the report should be attached (leave blank for none).
        required: false
      pr:
        description: PR number to which comment should be added (leave blank for none).
        required: false

name: qcthat Completed Issues Report

permissions:
  # Required for report.
  issues: read
  # Required to attach report to a release.
  contents: write
  # Required to add report to pull requests as a comment.
  pull-requests: write

jobs:
  qcthat-completed_issues:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v5

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: local::., Gilead-BioStats/qcthat@main

      - name: Generate Completed Issues QC Report
        run: |
          IssueTestMatrix <- qcthat::QCCompletedIssues()
          print(IssueTestMatrix)

          # Also save as a file to attach to the release.
          print(IssueTestMatrix, con = "qc_report.txt")

          # Also post as a comment.
          prNumber <- if ("${{ github.event_name }}" == "pull_request") {
            ${{ github.event.pull_request.number }}
          } else if ("${{ inputs.pr }}" != "") {
            ${{ inputs.pr }}
          } else {
            NA_integer_
          }

          if (!is.na(prNumber)) {
            qcthat::CommentReport(
              IssueTestMatrix,
              "Completed Issues",
              intPRNumber = prNumber
            )
          }
        shell: Rscript {0}

      # Delete or comment out this step to prevent reports from being attached to released tags.
      - name: Add to release
        if: github.event_name == 'release' || inputs.tag != ''
        uses: svenstaro/upload-release-action@v2
        with:
          file: qc_report.txt
          asset_name: qc_report_$tag.txt
          tag: ${{ github.event.release.tag_name || inputs.tag }}
          overwrite: true
