test_that("UpdateReleaseBody makes the expected call (#152)", {
  local_mocked_bindings(
    CallGHAPI = function(...) list(...)
  )
  test_result <- UpdateReleaseBody(
    strReleaseID = "releaseID",
    strBody = "New body content",
    strOwner = "owner",
    strRepo = "repo",
    strGHToken = "token"
  )
  expect_named(
    test_result,
    c("", "release_id", "body", "strOwner", "strRepo", "strGHToken")
  )
  expect_equal(
    test_result[[1]],
    "PATCH /repos/{owner}/{repo}/releases/{release_id}"
  )
})

test_that("UpdateReleaseBody uses existing body if available (#152)", {
  local_mocked_bindings(
    CallGHAPI = function(strEndpoint, ...) {
      if (stringr::str_starts(strEndpoint, "GET")) {
        return(list(body = "Existing body content"))
      }
      return(list(...))
    }
  )
  test_result <- UpdateReleaseBody(
    strReleaseID = "releaseID",
    strBody = "New body content",
    strOwner = "owner",
    strRepo = "repo",
    strGHToken = "token"
  )
  expect_equal(
    test_result$body,
    "Existing body content\n\n\nNew body content"
  )
})

test_that("AttachReleaseReports makes the expected calls (#152, #160)", {
  local_mocked_bindings(
    FormatReportType = function(fnReport, strReportType, ...) {
      paste("Formatted", strReportType)
    },
    CompileReleaseReportsMarkdown = function(chrBody, ...) {
      paste(chrBody, collapse = "\n\n\n")
    },
    UpdateReleaseBody = function(strReleaseID, strBody, ...) {
      expect_equal(strReleaseID, "releaseID")
      expect_equal(
        strBody,
        paste(
          c("Formatted Milestone", "Formatted Completed Issues"),
          collapse = "\n\n\n"
        )
      )
      cli::cli_inform("UpdateReleaseBody called")
    }
  )
  expect_message(
    {
      returned_value <- expect_invisible(
        AttachReleaseReports(
          strReleaseID = "releaseID",
          lglMilestone = TRUE,
          chrMilestones = "testmilestone",
          lglCompleted = TRUE,
          dfITM = "testdf",
          strOwner = "owner",
          strRepo = "repo",
          strGHToken = "token"
        )
      )
    },
    "UpdateReleaseBody called"
  )
  expect_equal(returned_value, "testdf")

  local_mocked_bindings(
    UpdateReleaseBody = function(strReleaseID, strBody, ...) {
      expect_equal(strReleaseID, "releaseID")
      expect_equal(
        strBody,
        "Formatted Completed Issues"
      )
      cli::cli_inform("UpdateReleaseBody called")
    }
  )
  expect_message(
    {
      returned_value <- expect_invisible(
        AttachReleaseReports(
          strReleaseID = "releaseID",
          lglMilestone = FALSE,
          chrMilestones = character(),
          lglCompleted = TRUE,
          dfITM = "testdf",
          strOwner = "owner",
          strRepo = "repo",
          strGHToken = "token"
        )
      )
    },
    "UpdateReleaseBody called"
  )
  expect_equal(returned_value, "testdf")
})

test_that("CompileReleaseReportsMarkdown stitches together parts for releases (#152)", {
  local_mocked_bindings(
    FetchRunURL = function(strRunID, ...) {
      expect_equal(strRunID, "runid")
      "runurl"
    },
    PrettyTimestamp = function() "timestamp",
    FormatSessionInfo = function() "sessioninfo"
  )
  expect_equal(
    {
      CompileReleaseReportsMarkdown(
        chrBody = c("Body part 1", "Body part 2"),
        strRunID = "runid",
        strOwner = "owner",
        strRepo = "repo",
        strGHToken = "token"
      )
    },
    paste(
      "## [{qcthat}](https://gilead-biostats.github.io/qcthat/) Reports",
      "Body part 1",
      "Body part 2",
      "This report was generated by [this GitHub Actions run](runurl).",
      "*Last updated: timestamp*",
      "sessioninfo",
      sep = "\n\n\n"
    )
  )
})

test_that("AttachReleaseReports runs properly on release (#181)", {
  ExpectUserAccepts(
    "AttachReleaseReports attaches reports to published releases",
    intIssue = 181,
    chrInstructions = "Navigate to [this release](https://github.com/Gilead-BioStats/qcthat/releases/tag/ForTesting)",
    chrChecks = c(
      "The release has a section titled 'qcthat Reports'",
      "The section contains a 'Milestone' report.",
      "The section contains a 'Completed Issues' report.",
      "The section links to the workflow run that generated the reports.",
      "The reports make sense and are aesthetically pleasing."
    )
  )
})
