test_that("CommentIssue compiles the body as expected (#83, #172)", {
  local_mocked_bindings(
    CommentIssueRaw = function(strBodyCompiled, ...) strBodyCompiled,
    PrettyTimestamp = function() "TIMESTAMP",
    FetchRunURL = function(...) "RUN URL",
    FormatSessionInfo = function() "SESSION INFO"
  )
  test_result <- CommentIssue(
    intIssue = 1,
    strTitle = "Test Title",
    strBody = "This is a test comment.",
    lglUpdate = FALSE,
    strOwner = "test-owner",
    strRepo = "test-repo",
    strGHToken = "test-token"
  )
  expect_equal(
    test_result,
    "## Test Title\n\nThis is a test comment.\n\nThis report was generated by [this GitHub Actions run](RUN URL).\n\n*Last updated: TIMESTAMP*\n\nSESSION INFO\n\n<!-- qcthat-comment-id: 0b0a574c2bcc14f97e3ee223d93f0032 -->"
  )
})

test_that("CommentIssue updates when told to do so (#83, #100, #123)", {
  local_mocked_bindings(
    CommentIssueRaw = function(...) stop("Should not be called"),
    UpdateIssueComment = function(...) "Success",
    PrettyTimestamp = function() "TIMESTAMP",
    FetchRunURL = function(...) "RUN URL",
    FormatSessionInfo = function() "SESSION INFO"
  )
  test_result <- CommentIssue(
    intIssue = 1,
    strTitle = "Test Title",
    strBody = "This is a test comment.",
    lglUpdate = TRUE,
    strOwner = "test-owner",
    strRepo = "test-repo",
    strGHToken = "test-token"
  )
  expect_equal(
    test_result,
    "Success"
  )
})

test_that("UpdateIssueComment updates when a comment exists (#83)", {
  local_mocked_bindings(
    FetchIssueCommentGHID = function(...) 12345,
    UpdateCommentRaw = function(...) "Success",
    CommentIssueRaw = function(...) stop("Should not be called")
  )
  test_result <- UpdateIssueComment(
    intIssue = 1,
    strBodyCompiled = "Updated comment body.",
    strCommentID = "test-comment-id",
    strOwner = "test-owner",
    strRepo = "test-repo",
    strGHToken = "test-token"
  )
  expect_equal(
    test_result,
    "Success"
  )
})

test_that("UpdateIssueComment creates when a comment doesn't exist (#83)", {
  local_mocked_bindings(
    FetchIssueCommentGHID = function(...) double(),
    UpdateCommentRaw = function(...) stop("Should not be called"),
    CommentIssueRaw = function(...) "Success"
  )
  test_result <- UpdateIssueComment(
    intIssue = 1,
    strBodyCompiled = "Updated comment body.",
    strCommentID = "test-comment-id",
    strOwner = "test-owner",
    strRepo = "test-repo",
    strGHToken = "test-token"
  )
  expect_equal(
    test_result,
    "Success"
  )
})

test_that("FetchIssueCommentGHID returns the correct GH ID when found (#83)", {
  local_mocked_bindings(
    CallGHAPI = function(...) {
      list(
        list(id = 11111, body = "Some other comment."),
        list(
          id = 22222,
          body = "## Title\n\nBody\n\n<!-- qcthat-comment-id: test-comment-id -->"
        ),
        list(id = 33333, body = "Another comment.")
      )
    }
  )
  test_result <- FetchIssueCommentGHID(
    intIssue = 1,
    strCommentID = "test-comment-id",
    strOwner = "test-owner",
    strRepo = "test-repo",
    strGHToken = "test-token"
  )
  expect_equal(
    test_result,
    22222
  )
})

test_that("FetchIssueCommentGHID returns nothing when no matching comment found (#83)", {
  local_mocked_bindings(
    CallGHAPI = function(...) {
      list(
        list(id = 11111, body = "Some other comment."),
        list(
          id = 22222,
          body = "Also not the comment."
        ),
        list(id = 33333, body = "Another comment.")
      )
    }
  )
  test_result <- FetchIssueCommentGHID(
    intIssue = 1,
    strCommentID = "nonexistent-comment-id",
    strOwner = "test-owner",
    strRepo = "test-repo",
    strGHToken = "test-token"
  )
  expect_equal(
    test_result,
    double()
  )
})

test_that("UpdateCommentRaw calls the API as expected (#83)", {
  local_mocked_bindings(
    CallGHAPI = function(...) list(...)
  )
  test_result <- UpdateCommentRaw(
    dblCommentGHID = 12345,
    strBodyCompiled = "Updated comment body.",
    strOwner = "test-owner",
    strRepo = "test-repo",
    strGHToken = "test-token"
  )
  expect_named(
    test_result,
    c("", "strOwner", "strRepo", "comment_id", "body", "strGHToken")
  )
  expect_equal(
    test_result[[1]],
    "PATCH /repos/{owner}/{repo}/issues/comments/{comment_id}"
  )
})

test_that("CommentIssueRaw calls the API as expected (#83)", {
  local_mocked_bindings(
    CallGHAPI = function(...) list(...)
  )
  test_result <- CommentIssueRaw(
    intIssue = 12345,
    strBodyCompiled = "New comment body.",
    strOwner = "test-owner",
    strRepo = "test-repo",
    strGHToken = "test-token"
  )
  expect_named(
    test_result,
    c("", "strOwner", "strRepo", "issue_number", "body", "strGHToken")
  )
  expect_equal(
    test_result[[1]],
    "POST /repos/{owner}/{repo}/issues/{issue_number}/comments"
  )
})

test_that("CommentIssue updates a comment as expected (#83)", {
  qcthat::ExpectUserAccepts(
    "CommentIssue updates a comment",
    intIssue = 83,
    chrChecks = c(
      "A new comment appears on the targeted issue.",
      "The comment updates when you re-comment"
    ),
    chrInstructions = 'Run this code. Make sure `strTitle` is unique, for example by changing "My" to your name.

```r
# Make this semi-unique, so it definitely will not use an existing comment.
strTitle <- "My Test Comment"
CommentIssue(
  83,
  strTitle = strTitle
  strBody = "This is a test comment created for testing purposes."
)
```

After confirming that step, run this code to update the comment.

```r
CommentIssue(
  83,
  strTitle = strTitle
  strBody = "This is an update to an existing comment."
)
```'
  )
})

test_that("CommentIssue includes run URL when available (#150)", {
  local_mocked_bindings(
    CommentIssueRaw = function(strBodyCompiled, ...) strBodyCompiled,
    PrettyTimestamp = function() "TIMESTAMP",
    FetchRunURL = function(strRunID, ...) {
      switch(
        strRunID,
        "no_jobs" = "https://link.to.run",
        "with_job" = "https://link.to.run/job/id",
        NULL
      )
    },
    FormatSessionInfo = function() ""
  )
  expect_snapshot({
    CommentIssue(
      intIssue = 123,
      strTitle = "title",
      strBody = "body",
      lglUpdate = FALSE,
      strRunID = "no_jobs",
      strOwner = "owner",
      strRepo = "repo",
      strGHToken = "token"
    )
  })
  expect_snapshot({
    CommentIssue(
      intIssue = 123,
      strTitle = "title",
      strBody = "body",
      lglUpdate = FALSE,
      strRunID = "with_job",
      strOwner = "owner",
      strRepo = "repo",
      strGHToken = "token"
    )
  })
  expect_snapshot({
    CommentIssue(
      intIssue = 123,
      strTitle = "title",
      strBody = "body",
      lglUpdate = FALSE,
      strRunID = "bad_run",
      strOwner = "owner",
      strRepo = "repo",
      strGHToken = "token"
    )
  })
})

test_that("FetchRunURL returns the expected URL (#150)", {
  local_mocked_bindings(
    FetchRunJobsRaw = function(strRunID, ...) {
      switch(
        strRunID,
        "one_job" = list(
          total_count = 1,
          jobs = list(list(html_url = "https://link.to.run/job/1"))
        ),
        "two_jobs" = list(
          total_count = 2,
          jobs = list(list(a = "a"), list(b = "b"))
        ),
        "no_jobs" = list(total_count = 0)
      )
    },
    FetchRunInfoRaw = function(strRunID, ...) {
      switch(
        strRunID,
        "two_jobs" = list(html_url = "https://link.to.run/with_jobs"),
        "no_jobs" = list(html_url = "https://link.to.run/no_jobs")
      )
    }
  )
  expect_equal(
    FetchRunURL(
      "one_job",
      strOwner = "owner",
      strRepo = "repo",
      strGHToken = "token"
    ),
    "https://link.to.run/job/1"
  )
  expect_equal(
    FetchRunURL(
      "two_jobs",
      strOwner = "owner",
      strRepo = "repo",
      strGHToken = "token"
    ),
    "https://link.to.run/with_jobs"
  )
  expect_equal(
    FetchRunURL(
      "no_jobs",
      strOwner = "owner",
      strRepo = "repo",
      strGHToken = "token"
    ),
    "https://link.to.run/no_jobs"
  )
})

test_that("FetchRunJobsRaw makes the expected call (#150)", {
  local_mocked_bindings(
    CallGHAPI = function(...) list(...)
  )
  expect_snapshot({
    FetchRunJobsRaw(
      "run_id",
      strOwner = "owner",
      strRepo = "repo",
      strGHToken = "token"
    )
  })
})

test_that("FetchRunInfoRaw makes the expected call (#150)", {
  local_mocked_bindings(
    CallGHAPI = function(...) list(...)
  )
  expect_snapshot({
    FetchRunInfoRaw(
      "run_id",
      strOwner = "owner",
      strRepo = "repo",
      strGHToken = "token"
    )
  })
})

test_that("CommentIssue includes session info (#150)", {
  local_mocked_bindings(
    CommentIssueRaw = function(strBodyCompiled, ...) strBodyCompiled,
    PrettyTimestamp = function() "TIMESTAMP",
    FetchRunURL = function(strRunID, ...) "RUN URL",
    GetRawSessionInfo = function() "Raw session info"
  )
  expect_snapshot({
    CommentIssue(
      intIssue = 123,
      strTitle = "title",
      strBody = "body",
      lglUpdate = FALSE,
      strRunID = "runID",
      strOwner = "owner",
      strRepo = "repo",
      strGHToken = "token"
    )
  })
})
