test_that("CommentIssue compiles the body as expected (#83, #172, #295)", {
  local_mocked_bindings(
    CommentIssueRaw = function(strBodyCompiled, ...) strBodyCompiled,
    PrettyTimestamp = function() "TIMESTAMP",
    ConstructJobURL = function(...) "JOB URL",
    LinkSessionInfo = function(...) "SESSION INFO",
    FetchJobID = function(...) "jobID"
  )
  test_result <- CommentIssue(
    intIssue = 1,
    strTitle = "Test Title",
    strBody = "This is a test comment.",
    lglUpdate = FALSE,
    strOwner = "test-owner",
    strRepo = "test-repo",
    strGHToken = "test-token"
  )
  expect_equal(
    test_result,
    "## Test Title\n\nThis is a test comment.\n\nThis report was generated by [this GitHub Actions job](JOB URL).\n\n*Last updated: TIMESTAMP*\n\nSESSION INFO\n\n<!-- qcthat-comment-id: 0b0a574c2bcc14f97e3ee223d93f0032 -->"
  )
})

test_that("CommentIssue updates when told to do so (#83, #100, #123, #295)", {
  local_mocked_bindings(
    CommentIssueRaw = function(...) stop("Should not be called"),
    UpdateIssueComment = function(...) "Success",
    PrettyTimestamp = function() "TIMESTAMP",
    ConstructJobURL = function(...) "JOB URL",
    LinkSessionInfo = function(...) "SESSION INFO",
    FetchJobID = function(...) "JOB_ID"
  )
  test_result <- CommentIssue(
    intIssue = 1,
    strTitle = "Test Title",
    strBody = "This is a test comment.",
    lglUpdate = TRUE,
    strOwner = "test-owner",
    strRepo = "test-repo",
    strGHToken = "test-token"
  )
  expect_equal(
    test_result,
    "Success"
  )
})

test_that("UpdateIssueComment updates when a comment exists (#83)", {
  local_mocked_bindings(
    FetchIssueCommentGHID = function(...) 12345,
    UpdateCommentRaw = function(...) "Success",
    CommentIssueRaw = function(...) stop("Should not be called")
  )
  test_result <- UpdateIssueComment(
    intIssue = 1,
    strBodyCompiled = "Updated comment body.",
    strCommentID = "test-comment-id",
    strOwner = "test-owner",
    strRepo = "test-repo",
    strGHToken = "test-token"
  )
  expect_equal(
    test_result,
    "Success"
  )
})

test_that("UpdateIssueComment creates when a comment doesn't exist (#83)", {
  local_mocked_bindings(
    FetchIssueCommentGHID = function(...) double(),
    UpdateCommentRaw = function(...) stop("Should not be called"),
    CommentIssueRaw = function(...) "Success"
  )
  test_result <- UpdateIssueComment(
    intIssue = 1,
    strBodyCompiled = "Updated comment body.",
    strCommentID = "test-comment-id",
    strOwner = "test-owner",
    strRepo = "test-repo",
    strGHToken = "test-token"
  )
  expect_equal(
    test_result,
    "Success"
  )
})

test_that("FetchIssueCommentGHID returns the correct GH ID when found (#83)", {
  local_mocked_bindings(
    CallGHAPI = function(...) {
      list(
        list(id = 11111, body = "Some other comment."),
        list(
          id = 22222,
          body = "## Title\n\nBody\n\n<!-- qcthat-comment-id: test-comment-id -->"
        ),
        list(id = 33333, body = "Another comment.")
      )
    }
  )
  test_result <- FetchIssueCommentGHID(
    intIssue = 1,
    strCommentID = "test-comment-id",
    strOwner = "test-owner",
    strRepo = "test-repo",
    strGHToken = "test-token"
  )
  expect_equal(
    test_result,
    22222
  )
})

test_that("FetchIssueCommentGHID returns nothing when no matching comment found (#83)", {
  local_mocked_bindings(
    CallGHAPI = function(...) {
      list(
        list(id = 11111, body = "Some other comment."),
        list(
          id = 22222,
          body = "Also not the comment."
        ),
        list(id = 33333, body = "Another comment.")
      )
    }
  )
  test_result <- FetchIssueCommentGHID(
    intIssue = 1,
    strCommentID = "nonexistent-comment-id",
    strOwner = "test-owner",
    strRepo = "test-repo",
    strGHToken = "test-token"
  )
  expect_equal(
    test_result,
    double()
  )
})

test_that("UpdateCommentRaw calls the API as expected (#83)", {
  local_mocked_bindings(
    CallGHAPI = function(...) list(...)
  )
  test_result <- UpdateCommentRaw(
    dblCommentGHID = 12345,
    strBodyCompiled = "Updated comment body.",
    strOwner = "test-owner",
    strRepo = "test-repo",
    strGHToken = "test-token"
  )
  expect_named(
    test_result,
    c("", "strOwner", "strRepo", "comment_id", "body", "strGHToken")
  )
  expect_equal(
    test_result[[1]],
    "PATCH /repos/{owner}/{repo}/issues/comments/{comment_id}"
  )
})

test_that("CommentIssueRaw calls the API as expected (#83)", {
  local_mocked_bindings(
    CallGHAPI = function(...) list(...)
  )
  test_result <- CommentIssueRaw(
    intIssue = 12345,
    strBodyCompiled = "New comment body.",
    strOwner = "test-owner",
    strRepo = "test-repo",
    strGHToken = "test-token"
  )
  expect_named(
    test_result,
    c("", "strOwner", "strRepo", "issue_number", "body", "strGHToken")
  )
  expect_equal(
    test_result[[1]],
    "POST /repos/{owner}/{repo}/issues/{issue_number}/comments"
  )
})

test_that("CommentIssue updates a comment as expected (#83)", {
  qcthat::ExpectUserAccepts(
    "CommentIssue updates a comment",
    intIssue = 83,
    chrChecks = c(
      "A new comment appears on the targeted issue.",
      "The comment updates when you re-comment"
    ),
    chrInstructions = 'Run this code. Make sure `strTitle` is unique, for example by changing "My" to your name.

```r
# Make this semi-unique, so it definitely will not use an existing comment.
strTitle <- "My Test Comment"
CommentIssue(
  83,
  strTitle = strTitle
  strBody = "This is a test comment created for testing purposes."
)
```

After confirming that step, run this code to update the comment.

```r
CommentIssue(
  83,
  strTitle = strTitle
  strBody = "This is an update to an existing comment."
)
```'
  )
})

test_that("CommentIssue includes job URL when available (#150, #295)", {
  local_mocked_bindings(
    CommentIssueRaw = function(strBodyCompiled, ...) strBodyCompiled,
    PrettyTimestamp = function() "TIMESTAMP",
    ConstructJobURL = function(strRunID, ...) {
      switch(
        strRunID,
        "no_jobs" = "https://link.to.run",
        "with_job" = "https://link.to.run/job/id",
        NULL
      )
    },
    LinkSessionInfo = function(...) "SESSION INFO",
    FetchJobID = function(...) "JOB_ID"
  )
  expect_snapshot({
    CommentIssue(
      intIssue = 123,
      strTitle = "title",
      strBody = "body",
      lglUpdate = FALSE,
      strRunID = "no_jobs",
      strOwner = "owner",
      strRepo = "repo",
      strGHToken = "token"
    )
  })
  expect_snapshot({
    CommentIssue(
      intIssue = 123,
      strTitle = "title",
      strBody = "body",
      lglUpdate = FALSE,
      strRunID = "with_job",
      strOwner = "owner",
      strRepo = "repo",
      strGHToken = "token"
    )
  })
  expect_snapshot({
    CommentIssue(
      intIssue = 123,
      strTitle = "title",
      strBody = "body",
      lglUpdate = FALSE,
      strRunID = "bad_run",
      strOwner = "owner",
      strRepo = "repo",
      strGHToken = "token"
    )
  })
})

test_that("CommentIssue includes session info (#150, #295)", {
  local_mocked_bindings(
    CommentIssueRaw = function(strBodyCompiled, ...) strBodyCompiled,
    PrettyTimestamp = function() "TIMESTAMP",
    ConstructJobURL = function(strRunID, strJobID, ...) "JOB URL",
    FetchSessionInfoStepNumber = function(...) 1L,
    FetchJobID = function(...) "JOB_ID"
  )
  expect_snapshot({
    CommentIssue(
      intIssue = 123,
      strTitle = "title",
      strBody = "body",
      lglUpdate = FALSE,
      strRunID = "runID",
      strJobName = "jobID",
      strOwner = "owner",
      strRepo = "repo",
      strGHToken = "token"
    )
  })
})

test_that("ConstructJobURL returns the correct URL when both run and job IDs are provided (#150, #295)", {
  expect_equal(
    ConstructJobURL(
      strRunID = "runID",
      strJobID = "jobID",
      strOwner = "owner",
      strRepo = "repo"
    ),
    "https://github.com/owner/repo/actions/runs/runID/job/jobID"
  )
})

test_that("FetchSessionInfoStepNumber returns the correct step number (#150, #295)", {
  local_mocked_bindings(
    CallGHAPI = function(...) {
      list(
        steps = list(
          list(name = "Step 1"),
          list(name = "Session info"),
          list(name = "Step 3")
        )
      )
    }
  )
  expect_equal(
    FetchSessionInfoStepNumber(
      strJobID = "jobID",
      strOwner = "owner",
      strRepo = "repo",
      strGHToken = "token"
    ),
    2L
  )
})
