#' Attach QC reports to a GitHub release
#'
#' Update a GitHub release with one or more QC reports, formatted in GitHub
#' markdown.
#'
#' @inheritParams shared-params
#' @returns `dfITM`, invisibly.
#' @export
AttachReleaseReports <- function(
  strReleaseID = GuessReleaseID(
    strOwner = strOwner,
    strRepo = strRepo,
    strGHToken = strGHToken
  ),
  lglCompleted = TRUE,
  lglMilestone = length(chrMilestones),
  chrMilestones = GuessMilestones(),
  dfITM = NULL,
  strRunID = Sys.getenv("GITHUB_RUN_ID"),
  strPkgRoot = ".",
  strOwner = GetGHOwner(),
  strRepo = GetGHRepo(),
  strGHToken = gh::gh_token(),
  lglWarn = TRUE,
  chrIgnoredLabels = DefaultIgnoreLabels(),
  envCall = rlang::caller_env()
) {
  if (length(strReleaseID) && (lglCompleted || lglMilestone)) {
    dfITM <- dfITM %||%
      QCPackage(
        strPkgRoot = strPkgRoot,
        strOwner = strOwner,
        strRepo = strRepo,
        strGHToken = strGHToken,
        chrIgnoredLabels = chrIgnoredLabels,
        envCall = envCall
      )

    chrBody <- character()
    if (lglMilestone && length(chrMilestones)) {
      chrBody <- c(
        chrBody,
        FormatReportType(
          fnReport = QCMilestones,
          strReportType = "Milestone",
          strPkgRoot = strPkgRoot,
          strOwner = strOwner,
          strRepo = strRepo,
          strGHToken = strGHToken,
          chrIgnoredLabels = chrIgnoredLabels,
          dfITM = dfITM,
          lOtherArgs = list(chrMilestones = chrMilestones),
          envCall = envCall
        )
      )
    }
    if (lglCompleted) {
      chrBody <- c(
        chrBody,
        FormatReportType(
          fnReport = QCCompletedIssues,
          strReportType = "Completed Issues",
          strPkgRoot = strPkgRoot,
          strOwner = strOwner,
          strRepo = strRepo,
          strGHToken = strGHToken,
          chrIgnoredLabels = chrIgnoredLabels,
          dfITM = dfITM,
          envCall = envCall
        )
      )
    }

    if (length(chrBody)) {
      UpdateReleaseBody(
        strReleaseID = strReleaseID,
        strBody = CompileReleaseReportsMarkdown(
          chrBody,
          strRunID = strRunID,
          strOwner = strOwner,
          strRepo = strRepo,
          strGHToken = strGHToken
        ),
        strOwner = strOwner,
        strRepo = strRepo,
        strGHToken = strGHToken
      )
    }
  }
  return(invisible(dfITM))
}

#' Update the body of a GitHub release
#'
#' @inheritParams shared-params
#' @returns The updated release object as returned by [gh::gh()].
#' @keywords internal
UpdateReleaseBody <- function(
  strReleaseID,
  strBody,
  strOwner = GetGHOwner(),
  strRepo = GetGHRepo(),
  strGHToken = gh::gh_token()
) {
  strExistingBody <- CallGHAPI(
    "GET /repos/{owner}/{repo}/releases/{release_id}",
    release_id = strReleaseID,
    strOwner = strOwner,
    strRepo = strRepo,
    strGHToken = strGHToken
  )$body

  if (length(strExistingBody)) {
    strBody <- paste(strExistingBody, strBody, sep = "\n\n\n")
  }

  CallGHAPI(
    "PATCH /repos/{owner}/{repo}/releases/{release_id}",
    release_id = strReleaseID,
    body = strBody,
    strOwner = strOwner,
    strRepo = strRepo,
    strGHToken = strGHToken
  )
}

#' Compile release reports in GitHub markdown
#'
#' @inheritParams shared-params
#' @returns A single string containing the compiled markdown.
#' @keywords internal
CompileReleaseReportsMarkdown <- function(
  chrBody,
  strRunID = Sys.getenv("GITHUB_RUN_ID"),
  strJobName = Sys.getenv("GITHUB_JOB"),
  strOwner = GetGHOwner(),
  strRepo = GetGHRepo(),
  strGHToken = gh::gh_token()
) {
  strJobID <- FetchJobID(
    strRunID = strRunID,
    strJobName = strJobName,
    strOwner = strOwner,
    strRepo = strRepo,
    strGHToken = strGHToken
  )
  strJobURL <- ConstructJobURL(
    strRunID = strRunID,
    strJobID = strJobID,
    strOwner = strOwner,
    strRepo = strRepo,
    strGHToken = strGHToken
  )
  strTime <- PrettyTimestamp()
  chrBody <- c(
    "## [{qcthat}](https://gilead-biostats.github.io/qcthat/) Reports",
    chrBody,
    glue::glue(
      "This report was generated by [this GitHub Actions job]({strJobURL})."
    ),
    glue::glue("*Reports generated: {strTime}*"),
    FormatSessionInfo()
  )
  paste(
    chrBody,
    collapse = "\n\n\n"
  )
}

#' Format session info in GitHub markdown
#'
#' @returns A string containing the session info formatted in GitHub markdown.
#' @keywords internal
FormatSessionInfo <- function() {
  lSess <- GetRawSessionInfo()
  oldCliWidth <- options(cli.width = 80)
  on.exit(options(oldCliWidth), add = TRUE)
  glue::glue(
    "<details>",
    "<summary>Session Info</summary>",
    paste(format(lSess), collapse = "\n\n"),
    "</details>",
    .sep = "\n"
  )
}

#' Get raw session info
#'
#' @returns The raw session info as returned by either
#'   [sessioninfo::session_info()] (if the `sessioninfo` package is installed)
#'   or [sessionInfo()].
#' @keywords internal
GetRawSessionInfo <- function() {
  # nocov start
  if (rlang::is_installed("utils")) {
    if (rlang::is_installed("sessioninfo")) {
      if (utils::packageVersion("sessioninfo") >= "1.2.1") {
        sessioninfo::session_info(pkgs = "installed", include_base = TRUE)
      } else {
        options(width = 200)
        sessioninfo::session_info(
          rownames(utils::installed.packages()),
          include_base = TRUE
        )
      }
    } else {
      utils::sessionInfo()
    }
  }
  # nocov end
}
