#' Comment on a GitHub Issue
#'
#' Create or update a comment on a GitHub issue with a standardized format.
#'
#' @inheritParams shared-params
#' @returns The comment object as returned by [gh::gh()], invisibly.
#' @export
#' @examplesIf interactive()
#' # This only works if you have an issue #1 in your repository.
#' CommentIssue(
#'   intIssue = 1,
#'   strTitle = "QC Report",
#'   strBody = "All checks passed successfully."
#' )
CommentIssue <- function(
  intIssue,
  strTitle,
  strBody,
  strCommentID = rlang::hash(strTitle),
  lglUpdate = TRUE,
  strRunID = Sys.getenv("GITHUB_RUN_ID"),
  strJobName = Sys.getenv("GITHUB_JOB"),
  strOwner = GetGHOwner(),
  strRepo = GetGHRepo(),
  strGHToken = gh::gh_token()
) {
  strJobID <- FetchJobID(
    strRunID = strRunID,
    strJobName = strJobName,
    strOwner = strOwner,
    strRepo = strRepo,
    strGHToken = strGHToken
  )
  strJobURL <- ConstructJobURL(
    strRunID = strRunID,
    strJobID = strJobID,
    strOwner = strOwner,
    strRepo = strRepo
  )
  strTime <- PrettyTimestamp()
  chrBody <- c(
    character(),
    strBody,
    glue::glue(
      "This report was generated by [this GitHub Actions job]({strJobURL})."
    ),
    glue::glue("*Last updated: {strTime}*"),
    LinkSessionInfo(strRunID, strJobID, strOwner, strRepo, strGHToken)
  )
  strBody <- paste(chrBody[nzchar(chrBody)], collapse = "\n\n")
  strBodyCompiled <- GlueEscaped(
    "## qcthatopen{strTitle}qcthatclose",
    strBody,
    "<!-- qcthat-comment-id: qcthatopen{strCommentID}qcthatclose -->"
  )
  if (lglUpdate) {
    return(
      UpdateIssueComment(
        intIssue = intIssue,
        strBodyCompiled = strBodyCompiled,
        strCommentID = strCommentID,
        strOwner = strOwner,
        strRepo = strRepo,
        strGHToken = strGHToken
      )
    )
  }
  CommentIssueRaw(
    intIssue = intIssue,
    strBodyCompiled = strBodyCompiled,
    strOwner = strOwner,
    strRepo = strRepo,
    strGHToken = strGHToken
  )
}

#' Update or create a comment on a GitHub issue
#'
#' @inheritParams shared-params
#' @returns The comment object as returned by [gh::gh()], invisibly.
#' @keywords internal
UpdateIssueComment <- function(
  intIssue,
  strBodyCompiled,
  strCommentID,
  strOwner = GetGHOwner(),
  strRepo = GetGHRepo(),
  strGHToken = gh::gh_token()
) {
  dblCommentGHID <- FetchIssueCommentGHID(
    intIssue = intIssue,
    strCommentID = strCommentID,
    strOwner = strOwner,
    strRepo = strRepo,
    strGHToken = strGHToken
  )
  if (length(dblCommentGHID)) {
    return(
      UpdateCommentRaw(
        dblCommentGHID = dblCommentGHID,
        strBodyCompiled = strBodyCompiled,
        strOwner = strOwner,
        strRepo = strRepo,
        strGHToken = strGHToken
      )
    )
  }
  CommentIssueRaw(
    intIssue = intIssue,
    strBodyCompiled = strBodyCompiled,
    strOwner = strOwner,
    strRepo = strRepo,
    strGHToken = strGHToken
  )
}

#' Fetch the GitHub ID of an issue comment by its qcthat comment ID
#'
#' @inheritParams shared-params
#' @returns The GitHub ID of the comment.
#' @keywords internal
FetchIssueCommentGHID <- function(
  intIssue,
  strCommentID,
  strOwner = GetGHOwner(),
  strRepo = GetGHRepo(),
  strGHToken = gh::gh_token()
) {
  FetchIssueComments(
    intIssue,
    strOwner = strOwner,
    strRepo = strRepo,
    strGHToken = strGHToken
  ) |>
    dplyr::filter(
      .data$qcthatCommentID == strCommentID
    ) |>
    dplyr::pull("CommentGHID")
}

#' Update a GitHub comment
#'
#' @inheritParams shared-params
#' @returns The comment object as returned by [gh::gh()], invisibly.
#' @keywords internal
UpdateCommentRaw <- function(
  dblCommentGHID,
  strBodyCompiled,
  strOwner = GetGHOwner(),
  strRepo = GetGHRepo(),
  strGHToken = gh::gh_token()
) {
  invisible(
    CallGHAPI(
      "PATCH /repos/{owner}/{repo}/issues/comments/{comment_id}",
      strOwner = strOwner,
      strRepo = strRepo,
      comment_id = dblCommentGHID,
      body = strBodyCompiled,
      strGHToken = strGHToken
    )
  )
}

#' Comment on a GitHub issue
#'
#' @inheritParams shared-params
#' @returns The comment object as returned by [gh::gh()], invisibly.
#' @keywords internal
CommentIssueRaw <- function(
  intIssue,
  strBodyCompiled,
  strOwner = GetGHOwner(),
  strRepo = GetGHRepo(),
  strGHToken = gh::gh_token()
) {
  invisible(
    CallGHAPI(
      "POST /repos/{owner}/{repo}/issues/{issue_number}/comments",
      strOwner = strOwner,
      strRepo = strRepo,
      issue_number = intIssue,
      body = strBodyCompiled,
      strGHToken = strGHToken
    )
  )
}

#' Construct the URL for a GitHub Actions job
#'
#' @inheritParams shared-params
#' @returns A string containing the URL for the specified GitHub Actions job.
#' @keywords internal
ConstructJobURL <- function(
  strRunID = character(),
  strJobID = character(),
  strOwner = GetGHOwner(),
  strRepo = GetGHRepo()
) {
  if (
    length(strRunID) && nzchar(strRunID) && length(strJobID) && nzchar(strJobID)
  ) {
    return(glue::glue(
      "https://github.com/{strOwner}/{strRepo}/actions/runs/{strRunID}/job/{strJobID}"
    ))
  }
}

#' Fetch the GitHub Actions job ID for a given run ID and job name
#'
#' @inheritParams shared-params
#' @returns The GitHub Actions job ID, or `NULL` if not found.
#' @keywords internal
FetchJobID <- function(
  strRunID = character(),
  strJobName = character(),
  strOwner = GetGHOwner(),
  strRepo = GetGHRepo(),
  strGHToken = gh::gh_token()
) {
  if (
    length(strRunID) &&
      nzchar(strRunID) &&
      length(strJobName) &&
      nzchar(strJobName)
  ) {
    lJobs <- CallGHAPI(
      "GET /repos/{owner}/{repo}/actions/runs/{run_id}/jobs",
      strOwner = strOwner,
      strRepo = strRepo,
      run_id = strRunID,
      strGHToken = strGHToken
    )$jobs

    intJobIndex <- purrr::detect_index(lJobs, \(job) {
      stringr::str_ends(tolower(job[["name"]]), tolower(strJobName))
    })

    if (intJobIndex > 0) {
      return(lJobs[[intJobIndex]][["id"]])
    }
  }
}

#' Construct the URL for the session info step of a GitHub Actions job
#'
#' @inheritParams shared-params
#' @returns A string containing the URL for the session info step (if any) in
#'   the specified GitHub Actions job.
#' @keywords internal
LinkSessionInfo <- function(
  strRunID = character(),
  strJobID = character(),
  strOwner = GetGHOwner(),
  strRepo = GetGHRepo(),
  strGHToken = gh::gh_token()
) {
  strJobURL <- ConstructJobURL(
    strRunID = strRunID,
    strJobID = strJobID,
    strOwner = strOwner,
    strRepo = strRepo
  )
  if (length(strJobURL) && nzchar(strJobURL)) {
    intSessionInfoStepNumber <- FetchSessionInfoStepNumber(
      strJobID = strJobID,
      strOwner = strOwner,
      strRepo = strRepo,
      strGHToken = strGHToken
    )
    if (length(intSessionInfoStepNumber) && intSessionInfoStepNumber > 0) {
      return(glue::glue(
        "[Session Info]({strJobURL}#step:{intSessionInfoStepNumber}:1)"
      ))
    }
  }
}

#' Fetch the session info step number for a GitHub Actions job
#'
#' @inheritParams shared-params
#' @returns The step number of the session info step, or `NULL` if not found.
#' @keywords internal
FetchSessionInfoStepNumber <- function(
  strJobID,
  strOwner = GetGHOwner(),
  strRepo = GetGHRepo(),
  strGHToken = gh::gh_token()
) {
  lJobInfo <- CallGHAPI(
    "GET /repos/{owner}/{repo}/actions/jobs/{job_id}",
    job_id = strJobID,
    strOwner = strOwner,
    strRepo = strRepo,
    strGHToken = strGHToken
  )
  intSessionInfoStepNumber <- purrr::detect_index(lJobInfo[["steps"]], \(step) {
    tolower(step[["name"]]) == "session info"
  })
}
