#' Comment on a PR or issue with a QC report
#'
#' Add or update a comment on a GitHub pull request (or issue) with a QC report,
#' formatted in GitHub markdown.
#'
#' @inheritParams shared-params
#'
#' @returns Invisibly returns the result of [CommentIssue()].
#' @export
CommentReport <- function(
  dfITM,
  strReportType,
  intPRNumber = GuessPRNumber(
    strOwner = strOwner,
    strRepo = strRepo,
    strGHToken = strGHToken
  ),
  lglUpdate = TRUE,
  strRunID = Sys.getenv("GITHUB_RUN_ID"),
  strOwner = GetGHOwner(),
  strRepo = GetGHRepo(),
  strGHToken = gh::gh_token()
) {
  strRunURL <- FetchRunURL(
    strRunID,
    strOwner = strOwner,
    strRepo = strRepo,
    strGHToken = strGHToken
  )
  CommentIssue(
    intPRNumber,
    strTitle = paste(
      "[{qcthat}](https://gilead-biostats.github.io/qcthat/) Report:",
      strReportType
    ),
    strBody = FormatReportGH(dfITM, strRunURL = strRunURL),
    lglUpdate = lglUpdate,
    strOwner = strOwner,
    strRepo = strRepo,
    strGHToken = strGHToken
  )
}

#' Format a QC report in GitHub markdown
#'
#' @inheritParams shared-params
#' @returns A string containing the report formatted in GitHub markdown.
#' @keywords internal
FormatReportGH <- function(dfITM, strRunURL = character()) {
  lOptions <- options(pillar.subtle = FALSE)
  on.exit(options(lOptions), add = TRUE)
  chrHeader <- FormatHeader(dfITM)
  chrBody <- c(FormatBody(dfITM), FormatKey())

  # I know I had a reason to add this but I can't currently find the situation
  # that triggers it.
  #
  # nocov start
  if (length(chrHeader) > 1) {
    chrBody <- c(chrHeader[-1], chrBody)
    chrHeader <- chrHeader[1]
  }
  # nocov end

  chrFooter <- FormatFooterMain(dfITM)
  chrFooter <- c(
    chrFooter[nzchar(chrFooter)],
    glue::glue(
      "This report was generated by [this GitHub Actions run]({strRunURL})."
    )
  )

  glue::glue(
    "<details>",
    "<summary>{chrHeader}</summary>",
    "",
    "```",
    paste(chrBody, collapse = "\n"),
    "```",
    "</details>",
    paste(chrFooter, collapse = "\n\n"),
    FormatSessionInfo(),
    .sep = "\n"
  )
}

#' Fetch the URL for a GitHub Actions run
#'
#' @inheritParams shared-params
#' @returns A string containing the URL for the specified GitHub Actions run,
#'   linking to the specific job when there is only one job.
#' @keywords internal
FetchRunURL <- function(
  strRunID = character(),
  strOwner = GetGHOwner(),
  strRepo = GetGHRepo(),
  strGHToken = gh::gh_token()
) {
  if (length(strRunID) && nzchar(strRunID)) {
    lRunJobs <- FetchRunJobsRaw(
      strRunID = strRunID,
      strOwner = strOwner,
      strRepo = strRepo,
      strGHToken = strGHToken
    )
    if (isTRUE(lRunJobs$total_count == 1)) {
      return(lRunJobs$jobs[[1]]$html_url)
    }
    lRunInfo <- FetchRunInfoRaw(
      strRunID = strRunID,
      strOwner = strOwner,
      strRepo = strRepo,
      strGHToken = strGHToken
    )
    return(lRunInfo$html_url)
  }
}

#' Fetch raw job info for a GitHub Actions run
#'
#' @inheritParams shared-params
#' @returns A list of raw job objects as returned by [gh::gh()].
#' @keywords internal
FetchRunJobsRaw <- function(
  strRunID,
  strOwner = GetGHOwner(),
  strRepo = GetGHRepo(),
  strGHToken = gh::gh_token()
) {
  CallGHAPI(
    "GET /repos/{owner}/{repo}/actions/runs/{run_id}/jobs",
    run_id = strRunID,
    strOwner = strOwner,
    strRepo = strRepo,
    strGHToken = strGHToken
  )
}

#' Fetch raw run info for a GitHub Actions run
#'
#' @inheritParams shared-params
#' @returns A list with the raw run object as returned by [gh::gh()].
#' @keywords internal
FetchRunInfoRaw <- function(
  strRunID,
  strOwner = GetGHOwner(),
  strRepo = GetGHRepo(),
  strGHToken = gh::gh_token()
) {
  CallGHAPI(
    "GET /repos/{owner}/{repo}/actions/runs/{run_id}",
    run_id = strRunID,
    strOwner = strOwner,
    strRepo = strRepo,
    strGHToken = strGHToken
  )
}

#' Format session info in GitHub markdown
#'
#' @returns A string containing the session info formatted in GitHub markdown.
#' @keywords internal
FormatSessionInfo <- function() {
  lSess <- GetRawSessionInfo()
  glue::glue(
    "<details>",
    "<summary>Session Info</summary>",
    paste(format(lSess), collapse = "\n"),
    "</details>",
    .sep = "\n"
  )
}

#' Get raw session info
#'
#' @returns The raw session info as returned by either
#'   [sessioninfo::session_info()] (if the `sessioninfo` package is installed)
#'   or [sessionInfo()].
#' @keywords internal
GetRawSessionInfo <- function() {
  # nocov start
  if (rlang::is_installed("sessioninfo")) {
    if (packageVersion("sessioninfo") >= "1.2.1") {
      sessioninfo::session_info(pkgs = "installed", include_base = TRUE)
    } else {
      options(width = 200)
      sessioninfo::session_info(
        rownames(installed.packages()),
        include_base = TRUE
      )
    }
  } else {
    sessionInfo()
  }
  # nocov end
}
