#' Comment on a GitHub Issue
#'
#' Create or update a comment on a GitHub issue with a standardized format.
#'
#' @inheritParams shared-params
#'
#' @returns The comment object as returned by [gh::gh()], invisibly.
#' @export
#'
#' @examplesIf interactive()
#' # This only works if you have an issue #1 in your repository.
#' CommentIssue(
#'   intIssue = 1,
#'   strTitle = "QC Report",
#'   strBody = "All checks passed successfully."
#' )
CommentIssue <- function(
  intIssue,
  strTitle,
  strBody,
  strCommentID = rlang::hash(strTitle),
  lglUpdate = TRUE,
  strRunID = Sys.getenv("GITHUB_RUN_ID"),
  strOwner = GetGHOwner(),
  strRepo = GetGHRepo(),
  strGHToken = gh::gh_token()
) {
  strRunURL <- FetchRunURL(
    strRunID,
    strOwner = strOwner,
    strRepo = strRepo,
    strGHToken = strGHToken
  )
  strTime <- PrettyTimestamp()
  chrBody <- c(
    character(),
    strBody,
    glue::glue(
      "This report was generated by [this GitHub Actions run]({strRunURL})."
    ),
    glue::glue("*Last updated: {strTime}*"),
    FormatSessionInfo()
  )
  strBody <- paste(chrBody[nzchar(chrBody)], collapse = "\n\n")
  strBodyCompiled <- GlueEscaped(
    "## qcthatopen{strTitle}qcthatclose",
    strBody,
    "<!-- qcthat-comment-id: qcthatopen{strCommentID}qcthatclose -->"
  )
  if (lglUpdate) {
    return(
      UpdateIssueComment(
        intIssue = intIssue,
        strBodyCompiled = strBodyCompiled,
        strCommentID = strCommentID,
        strOwner = strOwner,
        strRepo = strRepo,
        strGHToken = strGHToken
      )
    )
  }
  CommentIssueRaw(
    intIssue = intIssue,
    strBodyCompiled = strBodyCompiled,
    strOwner = strOwner,
    strRepo = strRepo,
    strGHToken = strGHToken
  )
}

#' Update or create a comment on a GitHub issue
#'
#' @inheritParams shared-params
#' @returns The comment object as returned by [gh::gh()], invisibly.
#' @keywords internal
UpdateIssueComment <- function(
  intIssue,
  strBodyCompiled,
  strCommentID,
  strOwner = GetGHOwner(),
  strRepo = GetGHRepo(),
  strGHToken = gh::gh_token()
) {
  dblCommentGHID <- FetchIssueCommentGHID(
    intIssue = intIssue,
    strCommentID = strCommentID,
    strOwner = strOwner,
    strRepo = strRepo,
    strGHToken = strGHToken
  )
  if (length(dblCommentGHID)) {
    return(
      UpdateCommentRaw(
        dblCommentGHID = dblCommentGHID,
        strBodyCompiled = strBodyCompiled,
        strOwner = strOwner,
        strRepo = strRepo,
        strGHToken = strGHToken
      )
    )
  }
  CommentIssueRaw(
    intIssue = intIssue,
    strBodyCompiled = strBodyCompiled,
    strOwner = strOwner,
    strRepo = strRepo,
    strGHToken = strGHToken
  )
}

#' Fetch the GitHub ID of an issue comment by its qcthat comment ID
#'
#' @inheritParams shared-params
#' @returns The GitHub ID of the comment.
#' @keywords internal
FetchIssueCommentGHID <- function(
  intIssue,
  strCommentID,
  strOwner = GetGHOwner(),
  strRepo = GetGHRepo(),
  strGHToken = gh::gh_token()
) {
  FetchIssueComments(
    intIssue,
    strOwner = strOwner,
    strRepo = strRepo,
    strGHToken = strGHToken
  ) |>
    dplyr::filter(
      .data$qcthatCommentID == strCommentID
    ) |>
    dplyr::pull("CommentGHID")
}

#' Update a GitHub comment
#'
#' @inheritParams shared-params
#' @returns The comment object as returned by [gh::gh()], invisibly.
#' @keywords internal
UpdateCommentRaw <- function(
  dblCommentGHID,
  strBodyCompiled,
  strOwner = GetGHOwner(),
  strRepo = GetGHRepo(),
  strGHToken = gh::gh_token()
) {
  invisible(
    CallGHAPI(
      "PATCH /repos/{owner}/{repo}/issues/comments/{comment_id}",
      strOwner = strOwner,
      strRepo = strRepo,
      comment_id = dblCommentGHID,
      body = strBodyCompiled,
      strGHToken = strGHToken
    )
  )
}

#' Comment on a GitHub issue
#'
#' @inheritParams shared-params
#' @returns The comment object as returned by [gh::gh()], invisibly.
#' @keywords internal
CommentIssueRaw <- function(
  intIssue,
  strBodyCompiled,
  strOwner = GetGHOwner(),
  strRepo = GetGHRepo(),
  strGHToken = gh::gh_token()
) {
  invisible(
    CallGHAPI(
      "POST /repos/{owner}/{repo}/issues/{issue_number}/comments",
      strOwner = strOwner,
      strRepo = strRepo,
      issue_number = intIssue,
      body = strBodyCompiled,
      strGHToken = strGHToken
    )
  )
}

#' Fetch the URL for a GitHub Actions run
#'
#' @inheritParams shared-params
#' @returns A string containing the URL for the specified GitHub Actions run,
#'   linking to the specific job when there is only one job.
#' @keywords internal
FetchRunURL <- function(
  strRunID = character(),
  strOwner = GetGHOwner(),
  strRepo = GetGHRepo(),
  strGHToken = gh::gh_token()
) {
  if (length(strRunID) && nzchar(strRunID)) {
    lRunJobs <- FetchRunJobsRaw(
      strRunID = strRunID,
      strOwner = strOwner,
      strRepo = strRepo,
      strGHToken = strGHToken
    )
    if (isTRUE(lRunJobs$total_count == 1)) {
      return(lRunJobs$jobs[[1]]$html_url)
    }
    lRunInfo <- FetchRunInfoRaw(
      strRunID = strRunID,
      strOwner = strOwner,
      strRepo = strRepo,
      strGHToken = strGHToken
    )
    return(lRunInfo$html_url)
  }
}

#' Fetch raw job info for a GitHub Actions run
#'
#' @inheritParams shared-params
#' @returns A list of raw job objects as returned by [gh::gh()].
#' @keywords internal
FetchRunJobsRaw <- function(
  strRunID,
  strOwner = GetGHOwner(),
  strRepo = GetGHRepo(),
  strGHToken = gh::gh_token()
) {
  CallGHAPI(
    "GET /repos/{owner}/{repo}/actions/runs/{run_id}/jobs",
    run_id = strRunID,
    strOwner = strOwner,
    strRepo = strRepo,
    strGHToken = strGHToken
  )
}

#' Fetch raw run info for a GitHub Actions run
#'
#' @inheritParams shared-params
#' @returns A list with the raw run object as returned by [gh::gh()].
#' @keywords internal
FetchRunInfoRaw <- function(
  strRunID,
  strOwner = GetGHOwner(),
  strRepo = GetGHRepo(),
  strGHToken = gh::gh_token()
) {
  CallGHAPI(
    "GET /repos/{owner}/{repo}/actions/runs/{run_id}",
    run_id = strRunID,
    strOwner = strOwner,
    strRepo = strRepo,
    strGHToken = strGHToken
  )
}

#' Format session info in GitHub markdown
#'
#' @returns A string containing the session info formatted in GitHub markdown.
#' @keywords internal
FormatSessionInfo <- function() {
  lSess <- GetRawSessionInfo()
  oldCliWidth <- options(cli.width = 80)
  on.exit(options(oldCliWidth), add = TRUE)
  glue::glue(
    "<details>",
    "<summary>Session Info</summary>",
    paste(format(lSess), collapse = "\n\n"),
    "</details>",
    .sep = "\n"
  )
}

#' Get raw session info
#'
#' @returns The raw session info as returned by either
#'   [sessioninfo::session_info()] (if the `sessioninfo` package is installed)
#'   or [sessionInfo()].
#' @keywords internal
GetRawSessionInfo <- function() {
  # nocov start
  if (rlang::is_installed("utils")) {
    if (rlang::is_installed("sessioninfo")) {
      if (utils::packageVersion("sessioninfo") >= "1.2.1") {
        sessioninfo::session_info(pkgs = "installed", include_base = TRUE)
      } else {
        options(width = 200)
        sessioninfo::session_info(
          rownames(utils::installed.packages()),
          include_base = TRUE
        )
      }
    } else {
      utils::sessionInfo()
    }
  }
  # nocov end
}
