# Deploy the pkgdown site (often a test version).

on:
  push:
    branches: [main, dev]
  pull_request:
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v5

      - name: Set Development Mode Env Var
        if: github.ref_name != 'main'
        run: |
          echo "Ref is '${{ github.ref_name }}', setting PKGDOWN_DEV_MODE=devel"
          echo "PKGDOWN_DEV_MODE=devel" >> $GITHUB_ENV

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Render slides
        run: Rscript -e 'source("slides/render_slides.R")'

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy PR preview 🧪
        if: github.event_name == 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          # Don't clean the whole branch, just the target folder
          clean: false
          branch: gh-pages
          folder: docs
          # Deploy to a subdirectory named after the PR number
          target-folder: pr/${{ github.event.number }}

      - name: Comment with PR site URL 🌐
        if: github.event_name == 'pull_request'
        run: |
          intPRNumber <- ${{ github.event.pull_request.number }}
          strOwner <- tolower(qcthat::GetGHOwner())
          strRepo <- qcthat::GetGHRepo()
          strURL <- glue::glue(
            "https://{strOwnerIO}.github.io/{strRepo}/pr/{intPRNumber}/dev"
          )
          print(paste("🌐 URL:", strURL))
          qcthat::CommentIssue(
            intPRNumber,
            glue::glue("🌐 [PR pkgdown deployed]({strURL})"),
            NULL
          )
        shell: Rscript {0}

      - name: Deploy pkgdown 📃
        if: github.event_name != 'pull_request'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
