on:
  push:
    branches: [main]
  pull_request:
    types: [opened, edited, reopened, synchronize, milestoned]
  release:
    types: [released]
  issues:
    types: [closed]
  workflow_dispatch:
    inputs:
      pr:
        description: PR number to which reports should be added (leave blank for none).
        required: false
      milestone:
        description: Milestone name to use for the milestone report (leave blank for none).
        required: false
      tag:
        description: Release tag to which the report should be attached (leave blank for none).
        required: false
      issueNumber:
        description: The closed issue number to process to update user acceptance testing information.
        required: false

name: qcthat Quality Control

permissions:
  # read: Required for generating reports and updating UAT status.
  # write: Required for initiating the UAT process.
  issues: write
  # read: Required for updating UAT status.
  # write: Required for adding reports to pull requests.
  pull-requests: write
  # write: Required for attaching reports to releases.
  contents: write
  # write: Required for updating UAT status.
  actions: write

jobs:
  qcthat:
    runs-on: ubuntu-latest
    if: >-
      (github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'qcthat-uat')) ||
      github.event_name != 'issues'
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v5

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: local::.

      - name: Manage User Acceptance Testing
        if: >-
          (github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'qcthat-uat')) ||
          (github.event_name == 'workflow_dispatch' && inputs.issueNumber != '')
        run: |
          Rscript -e "qcthat::TriggerUAT()"

      - name: Generate Issue-Test Matrix
        if: >-
          github.event_name == 'push' ||
          github.event_name == 'pull_request' ||
          github.event_name == 'release' ||
          (github.event_name == 'workflow_dispatch' && inputs.issueNumber == '')
        env:
          qcthat_UAT: true
        run: |
          # Generate the full matrix for the package
          IssueTestMatrix <- qcthat::QCPackage()
          print(IssueTestMatrix)

          # Save the matrix and UAT data for subsequent steps
          saveRDS(IssueTestMatrix, "itm.rds")
          qcthat::SaveUATIssues()
        shell: Rscript {0}

      - name: Update PR Reports
        if: >-
          github.event_name == 'pull_request' ||
          (github.event_name == 'workflow_dispatch' && inputs.pr != '')
        run: |
          issueTestMatrix <- readRDS("itm.rds")
          qcthat::LoadUATIssues()
          qcthat::CommentPRReports(dfIssueTestMatrix = issueTestMatrix)
        shell: Rscript {0}

      - name: Update Release Reports
        if: github.event_name == 'release' || inputs.tag != ''
        run: |
          issueTestMatrix <- readRDS("itm.rds")
          qcthat::LoadUATIssues()
          qcthat::AttachReleaseReports(dfIssueTestMatrix = issueTestMatrix)
        shell: Rscript {0}
