# name: R-CMD-check.yaml
# version: 0.4.1
# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Description: R CMD check for PRs
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
name: R-CMD-check
permissions: read-all
jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Define matrix based on target branch
        id: set-matrix
        uses: gilead-biostats/gsm.utils/setup-matrix-with-dev@actions-v1
        with:
          pkg-use: 'public'
  R-CMD-check:
    needs: [setup-matrix]
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJSON(needs.setup-matrix.outputs.matrix) }}
    env:
      R_KEEP_PKG_SOURCE: yes
    steps:
      - name: Generate token
        uses: gilead-biostats/gsm.utils/generate-token@actions-v1
        id: token
        with:
          app-id: ${{ secrets.CM_BOT_APP_ID }}
          app-private-key: ${{ secrets.CM_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Check out repo
        uses: gilead-biostats/gsm.utils/checkout@actions-v1
        with:
          token: ${{ steps.token.outputs.token }}
      - name: Install R and dependencies
        uses: gilead-biostats/gsm.utils/install@actions-v1
        with:
          token: ${{ steps.token.outputs.token }}
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
          extra-packages: any::rcmdcheck
          needs: check
      - name: Set GITHUB_PAT
        run: echo "GITHUB_PAT=${{ steps.token.outputs.token }}" >> $GITHUB_ENV
      - name: Check package
        uses: gilead-biostats/gsm.utils/check-r-package@actions-v1
        with:
          error-on: ${{ matrix.config.error-on || '"warning"' }}
