# name: test-coverage.yaml
# version: 0.3.8
# Description: Compute test coverage and publish coverage-summary.json artifact
name: test-coverage
on:
  push:
    branches: [main, dev]
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [published]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: write
  pull-requests: write
jobs:
  call-test-coverage-core:
    uses: Gilead-BioStats/gsm.utils/.github/workflows/test-coverage-core.yaml@actions-v1
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
