# name: workflow-template-check.yaml
# version: 0.4.1
# Description: Check if GitHub Actions workflows match gsm.utils templates
name: Workflow Template Compliance Check
on:
  pull_request:
    branches: [main, release, dev]
    types: [opened, synchronize, reopened]
permissions:
  # Required to write comments on the pull request and view files
  pull-requests: write
  contents: read
jobs:
  check-workflows:
    uses: Gilead-BioStats/gsm.utils/.github/workflows/workflow-template-checker.yaml@actions-v1
    secrets:
      app-id: ${{ secrets.CM_BOT_APP_ID }}
      app-private-key: ${{ secrets.CM_BOT_PRIVATE_KEY }}
